### ISSUE TITLE
Internal Server Error after guest login.

### ISSUE THREAD

**Issue by Premitium** [oneall/social-login-prestashop#15]
The facebook login seems to work however, when the user is redirected back to the store. A form opens up and the user must confirm the registration. When choosing to confirm a server error 500 occurs.

No user is created in the database.

Any idea what might be going on?

Using prestashop 1.6.x

**Comment by SchlesserClaude** [comment]
Have you been able to fix the issue or why did you close it?

**Comment by yoshua9** [comment]
Same problem!
