### ISSUE TITLE
getting 403 error

### ISSUE THREAD

**Issue by husein522** [oneall/social-login-prestashop#19]
Hi,

I am getting 403 Forbidden error while login to google.

 

https://saifkart.com/mystore/module/socialloginizer/google?state=adf&code=zxcz&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile#

 

scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile#

 

I am getting error in in scope when i remove "https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile#"

it works fine.

I tried to modify code but could not suceed.

need help

 

Thanks

husein﻿

**Comment by SchlesserClaude** [comment]
Hello,

in the url you can see "socialloginizer". This is from a different plugin, not ours.

Regards,
