### ISSUE TITLE
Only include JS when its needed

### ISSUE THREAD

**Issue by humpfreybogart** [oneall/social-login-prestashop#8]
Hi 
Im wondering if there is a way to limit the inclusion of JS:
http://myusername.api.oneall.com/socialize/library.js

In these times site speed is important and I cant see a reason to include this script on pages where social login isnt available at all. Aggree? 
If Im right, is there a way to fix?

**Comment by SchlesserClaude** [comment]
Hi Michael, the library is included everywhere because we can't predict where the PrestaShop admins want to display the icons. It's very small and the browser will cache it after the first read, so it should not impact the speed of the page.

You can include it only where it's needed, but this will involve a bit of tinkering ;)

**Comment by michaelhjulskov** [comment]
I been thinking you could make some JS onload that is looking for 
onload :
if ($("div.oneall_social_login_providers")) 
  do the include

**Comment by humpfreybogart** [comment]
I been thinking you could make some JS onload like
if ($("#oneall_social_login").length) 
do the include

**Comment by michaelhjulskov** [comment]
i tried this: (and it didnt work)
`{if {$oasl_widget_location} eq 'library'}
	<script type="text/javascript">
	
		/* OneAll Social Login */
		/* http://docs.oneall.com/plugins/guide/social-login-prestashop/ */
		
		$(document).ready(function() {  
			if ($("#oneall_social_login").length){
				/* Asynchronous Library */      
				var oa = document.createElement('script');
				oa.type = 'text/javascript'; oa.async = true;
				oa.src = '//{$oasl_subdomain}.api.oneall.com/socialize/library.js';
				var s = document.getElementsByTagName('script')[0];
				s.parentNode.insertBefore(oa, s);
				
				/* Custom Hooks */      
				var _oneall = _oneall || [];                
				if (typeof oneallsociallogin !== 'undefined') {
					oneallsociallogin (_oneall, [{$oasl_widget_providers}], '{$oasl_auth_disable}', '{$oasl_auth_title}', '{$oasl_custom_title}');
				} else {
					throw new Error("OneAll Social Login is not correctly installed, the required file oneallsocialogin.js is not included.");
				}
			}
		});
	</script>
{/if}`

**Comment by humpfreybogart** [comment]
Solved by adding positions exceptions to the header hook

**Comment by ghost** [comment]
@michaelhjulskov please document the process for googlers ;)

**Comment by rockers007** [comment]
@michaelhjulskov  :please let me process,we r also facing same issue

**Comment by humpfreybogart** [comment]
As I remember it... Go to hooks and select the oneall hook and add exceptions, just add all views that shouldn't/doesn't show the oneall. If you need further information please contact me again and I can help if you pay for an hour or max two hours.
